langchain4j:
  open-ai:
    chat-model:
      # Api key
      api-key: sk-xxx
      # 模型
      model-name: qwen-turbo
      # 模型平台基础url
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
